export const collections = [
    "sub-admin",
    "parentcategories",
    "subcategories",
    "tax",
    "id",
    "membership",
    "reports",
    "item_requirement",
    "item_sale_report",
    "tax_report",
    "store_notifications",
    "user_notifications",
    "driver_notifications",
    "users",
    "Adminproducts",
    "storeProducts",
    "cities",
    "area",
    "storeList",
    "storepayments",
    "storeapproval",
    "orders",
    "pending orders",
    "cancelled orders",
    "ongoingorders",
    "out for orders",
    "payment failed orders",
    "completed orders",
    "day wise orders",
    "missed orders",
    "payout requests",
    "payouts",
    "rewards",
    "reedm value",
    "deliveryboy",
    "deliveryboy_incentives",
    "pages About",
    "termsAnd Conditions",
    "Userfeedback",
    "storefeedback",
    "deliveryboyfeedback",
    "usercallbackrequests",
    "storecallbackrequests",
    "deliveryboycallbackrequests",
    "Globalsettings",
    "SMS Settings",
    "FCM keys",
    "payment mode",
    "map settings",
    "driver incentive",
    "app link",
    "img store",
    "app notice",
    "cancelling reason",
    "Wallet_Rechage_History"
];

export const collectionSet = new Set(collections);
